# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

build_path = "build"
sh "mkdir -p #{build_path}"

default_platform(:ios)

platform :ios do
  desc "Clone source code"
  desc "#### Options"
  desc "* **source_code_url** source code git url"
  desc "* **target_path** target path to clone source code"
  lane :clone_source_code do |options|
    source_code_url = options[:source_code_url]
    target_path = options[:target_path]
    sh "git clone #{source_code_url} #{target_path}"
  end
  desc "build AlitaNativeLib.framework"
  desc "#### Options"
  desc "* **source_code_url** source code git url"
  lane :build_framework do |options|
    source_code_url = options[:source_code_url]
    sh "mkdir -p #{build_path}"
    target_path = "#{build_path}/micro-app"
    clone_source_code(source_code_url: source_code_url, target_path: target_path)
    sh "cd #{target_path}
    bundle exec fastlane build_AlitaNative
    "
    framework_path = "#{target_path}/build/AlitaNativeLib.framework"
    if (Dir.exist? "#{framework_path}")
      sh "cp -R #{framework_path} ../"
    else
      raise "build framework fail"
    end
  end
end
